package com.example.bookcourt.ui.theme

import androidx.compose.ui.graphics.Color

val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)
val OrangeStatusColor = Color(0xFFF3B71D)
val BackGroundWhite = Color(0xFFFAF8F2)
val TextFieldGrey = Color(0xFFECECEC)
val TextPlaceHolderColor = Color(0xFF1D1D1D)
val PrimaryText = Color(0xFF272727)
val SecondaryText = Color(0xFF8C8C8C)
val GrayText = Color(0xFF8C8C8C)
val GreenText = Color(0xFF30B25D)
val GrayBackground = Color(0xFFEFEBDE)
val Brown = Color(0xFF483936)
val LightBrown = Color(0xFFB2AC8B)
val BrightOlive = Color(0xFF6DCA7C)
val Shadow = Color(0xFF242424)
val TopAuthorsLightPink = Color(0xFFFBECE5)
val TopGenresLightPink = Color(0xFFFFE5EC)
val AppLogoBlack = Color(0xFF393939)
val ZaryaBackground = Color(0xFFF7F7F7)
val IgraSlovBackground = Color(0xFFDED2A9)
val LightPinkBackground = Color(0xFFFFE5D9)
val LighterPinkBackground = Color(0xFFFEFAE0)
val LightYellowBtn = Color(0xFFFCE181)
val MenuBackGround = Color(0xFFF9F7F1)
val SelectedMenuItem = Color(0xFFE8E4D7)
val ActiveProgressGrey = Color(0xFF868686)
val InactiveProgressGrey = Color(0xFFCFBFC4)
val SearchFieldBackground = Color(0xFFFEFEFE)
val MainBgColor = Color(0xFFFAF8F2)
val VerificationCodeBg = Color(0xFFEEEADD)
val DisabledBtnBg = Color(0xFFEFEBDE)
val DisabledBtnText = Color(0xFF8C8C8C)
val EmptyStatsBackground = Color(0xFFEBE0EA)
val LightGreyColor = Color(0xFF4E4E4E)
