package com.example.bookcourt.utils

import androidx.compose.ui.unit.sp

data class Dimens(
    val paddingSmall: Int,
    val paddingNormal: Int,
    val paddingBig: Int,
    val recommendationCardWidth: Int,
    val iconSizeExtraSmall:Int,
    val iconSizeSmall: Int,
    val iconSizeNormal: Int,
    val iconSizeBig: Int,
    val recommendationBottomSheet:Int,
    val bottomNavMenuIconSize:Int,
    val countBasketItemsSize:Int,
    val countBasketItemPaddingEnd:Int,
    val bookCardHeight:Int,
    val bookCardButtonSize:Int,
    val bookCardRatingBarSize:Int,
    val leaveFeedbackRatingBarSize:Int,
    val listFeedbacksRatingBarSize:Int,
    val basketBookCardHeight:Int,
    val amountButtonsSize:Int,
    val amountButtonsHeight:Int,
)


val CompactSmallDimens = Dimens(
    paddingSmall = 4,
    paddingNormal = 8,
    paddingBig = 10,
    recommendationCardWidth = 220,
    iconSizeSmall = 14,
    iconSizeExtraSmall=10,
    iconSizeNormal = 25,
    iconSizeBig = 32,
    recommendationBottomSheet = 0,
    bottomNavMenuIconSize = 18,
    countBasketItemsSize = 14,
    countBasketItemPaddingEnd = 7,
    bookCardHeight = 260,
    bookCardButtonSize = 35,
    bookCardRatingBarSize = 22,
    leaveFeedbackRatingBarSize =21,
    listFeedbacksRatingBarSize = 16,
    basketBookCardHeight = 120,
    amountButtonsSize = 23,
    amountButtonsHeight = 30,
)

val CompactMediumDimens = Dimens(
    paddingSmall = 8,
    paddingNormal = 10,
    paddingBig = 18,
    recommendationCardWidth = 250,
    iconSizeSmall = 20,
    iconSizeExtraSmall = 13,
    iconSizeNormal = 28,
    iconSizeBig = 35,
    recommendationBottomSheet = 0,
    bottomNavMenuIconSize = 24,
    countBasketItemsSize = 20,
    countBasketItemPaddingEnd = 12,
    bookCardHeight = 320,
    bookCardButtonSize = 48,
    bookCardRatingBarSize = 29,
    leaveFeedbackRatingBarSize =28,
    listFeedbacksRatingBarSize = 18,
    basketBookCardHeight = 150,
    amountButtonsSize = 30,
    amountButtonsHeight = 35,
)

val CompactDimens = Dimens(
    paddingSmall = 8,
    paddingNormal = 12,
    paddingBig = 18,
    recommendationCardWidth = 300,
    iconSizeSmall = 22,
    iconSizeExtraSmall = 13,
    iconSizeNormal = 28,
    iconSizeBig = 40,
    recommendationBottomSheet = 0,
    bottomNavMenuIconSize = 24,
    countBasketItemsSize = 20,
    countBasketItemPaddingEnd = 12,
    bookCardHeight = 320,
    bookCardButtonSize = 48,
    bookCardRatingBarSize = 29,
    leaveFeedbackRatingBarSize =28,
    listFeedbacksRatingBarSize = 18,
    basketBookCardHeight = 150,
    amountButtonsSize = 30,
    amountButtonsHeight = 35,
)

val MediumDimens = Dimens(
    paddingSmall = 14,
    paddingNormal = 16,
    paddingBig = 20,
    recommendationCardWidth = 300,
    iconSizeSmall = 24,
    iconSizeExtraSmall = 13,
    iconSizeNormal = 30,
    iconSizeBig = 50,
    recommendationBottomSheet = 0,
    bottomNavMenuIconSize = 24,
    countBasketItemsSize = 20,
    countBasketItemPaddingEnd = 12,
    bookCardHeight = 320,
    bookCardButtonSize = 48,
    bookCardRatingBarSize = 29,
    leaveFeedbackRatingBarSize =28,
    listFeedbacksRatingBarSize = 18,
    basketBookCardHeight = 150,
    amountButtonsSize = 30,
    amountButtonsHeight = 35,
)

val ExpandedDimens = Dimens(
    paddingSmall = 0,
    paddingNormal = 0,
    paddingBig = 0,
    recommendationCardWidth = 500,
    iconSizeSmall = 0,
    iconSizeExtraSmall = 13,
    iconSizeNormal = 0,
    iconSizeBig = 0,
    recommendationBottomSheet = 0,
    bottomNavMenuIconSize = 24,
    countBasketItemsSize = 20,
    countBasketItemPaddingEnd = 12,
    bookCardHeight = 320,
    bookCardButtonSize = 48,
    bookCardRatingBarSize = 29,
    leaveFeedbackRatingBarSize =28,
    listFeedbacksRatingBarSize = 18,
    basketBookCardHeight = 150,
    amountButtonsSize = 30,
    amountButtonsHeight = 35,
)
